### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by m-star18** [Gin-mmsm/image-calculator#34]
`Traceback (most recent call last):
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/m_star18/PycharmProjects/image-calculator/src/views.py", line 29, in upload_file
    txt, frame_img = ocr_image(filepath=filepath)
  File "/home/m_star18/PycharmProjects/image-calculator/src/calculator.py", line 39, in ocr_image
    fnt = ImageFont.truetype(r"../fonts/Apple Symbols.ttf", size=40)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/m_star18/PycharmProjects/image-calculator/venv/lib/python3.7/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine`

Apple Symbols.ttfが関係してそうな感じがします。

**Comment by m-star18** [comment]
ここでエラーが出てました
views.py
`txt, frame_img = ocr_image(filepath=filepath)`
calculator.py
`​fnt = ImageFont.truetype(r"../fonts/Apple Symbols.ttf", size=40`

**Comment by Gin-mmsm** [comment]
fontsに入ってるのに読めないのか...

**Comment by Gin-mmsm** [comment]
pillowが勝手にシステムのフォント読んでくれてる説

**Comment by m-star18** [comment]
これPillowのやつだったんですね、、

**Comment by Gin-mmsm** [comment]
これももしかしてstaticに入れたら動いたりする？

**Comment by Gin-mmsm** [comment]
この問題、こっちの環境で再現できないので @m-star18 @atsuki0727 にお任せしたいです...！

**Comment by m-star18** [comment]
このエラー、パスをr"fonts/Apple Symbols.ttf"にしたら上手くいったのですがそれでも大丈夫ですか？

**Comment by Gin-mmsm** [comment]
なぜそれなら動くんだ... たぶんwindowsでそれで動くなら問題ないのかな...？システムにもそのフォントないよね...？

**Comment by m-star18** [comment]
多分ですが相対パスのスタートが全てプロジェクトディレクトリに設定されてるからっぽいです

**Comment by Gin-mmsm** [comment]
なるほど！その修正pushできる？

**Comment by m-star18** [comment]
夜で大丈夫なら可能です！

**Comment by Gin-mmsm** [comment]
あ、そっか動けないのか...ごめん！こっちでやっとく！

**Comment by m-star18** [comment]
ありがとうございます🙇‍♂️🙇‍♂️
