### ISSUE TITLE
デプロイ後

### ISSUE THREAD

**Issue by Gin-mmsm** [Gin-mmsm/image-calculator#46]
デプロイできたけど500errorになってしまう...
![image](https://user-images.githubusercontent.com/62585233/93592317-ec489800-f9ec-11ea-9ca7-f2ee4e458a3c.png)

**Comment by Gin-mmsm** [comment]
buildpack-apt とconfig vars の設定はしてある...

**Comment by Gin-mmsm** [comment]
TESSDATA_PREFIXを直したら、動きはするけど、FileNotFoundError!!が出るように...

**Comment by Gin-mmsm** [comment]
@m-star18 heroku詳しかったりする...？

**Comment by m-star18** [comment]
全く触ったことないです🙇‍♂️🙇‍♂️🙇‍♂️

heroku logs --tail

を実行してみてほしいです

**Comment by Gin-mmsm** [comment]
log はこんな感じ
![image](https://user-images.githubusercontent.com/62585233/93595863-74ca3700-f9f3-11ea-936b-2d65a25d3f25.png)
filepathの問題なのかな...

**Comment by Gin-mmsm** [comment]
保存からうまくいってないみたいなんだよね...

**Comment by Gin-mmsm** [comment]
herokuは画像をバイトにしないとuploadできないと言う情報が...

**Comment by m-star18** [comment]
@Gin-mmsm @
実行してみたのですが、上手く動作してました

**Comment by Gin-mmsm** [comment]
ん、heroku上？

**Comment by m-star18** [comment]
sample.pngは想定通り動作しました👍

**Comment by m-star18** [comment]
今更なのですが、sampleに合わせて
/ => 1
K => 4
B => 8(これはありました)
とする変換を追加するのはどうでしょうか

**Comment by Gin-mmsm** [comment]
元から入ってるやつならいけるけど、web上でformから新たにファイルを生成できないらしい...

**Comment by Gin-mmsm** [comment]
あ、確かにそれいいね

**Comment by m-star18** [comment]
やばいですねそれやってみます、、、、、

**Comment by m-star18** [comment]
スマホで開くとエラー出ましたね、、、![image](https://user-images.githubusercontent.com/52071380/93597685-6af60300-f9f6-11ea-9caa-715806ef3dca.png)

**Comment by Gin-mmsm** [comment]
ぴえん ローカルで実演するか...？

**Comment by m-star18** [comment]
新たなファイルが生成できないバグはローカル上でもだめでした

**Comment by Gin-mmsm** [comment]
え、まじ...？ こっちの環境だとローカルなら動くな...

**Comment by atsuki0727** [comment]
このバグは新たなファイルが生成できないバグでしょうか？

TypeError
TypeError: cannot unpack non-iterable NoneType object

Traceback (most recent call last)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\atsuk\anaconda3\envs\image-calculator\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\atsuk\Desktop\image-calculator\src\views.py", line 29, in upload_file
txt, frame_img = ocr_image(filepath="src/" + filepath)
TypeError: cannot unpack non-iterable NoneType object
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by atsuki0727** [comment]
ローカルで試してみたところ何回やってもこのエラーが出てしまいました
